// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT14kS68DEQlltmW5q53z1dAjbcXMAH54',
    appId: '1:416340531176:web:7cf3b68099e1858a40f65d',
    messagingSenderId: '416340531176',
    projectId: 'bd-app-epis',
    authDomain: 'bd-app-epis.firebaseapp.com',
    storageBucket: 'bd-app-epis.firebasestorage.app',
    measurementId: 'G-GJ5JF1JSQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0uL7j_XzNBJL7LeThGH_KzI8Dc62Np0M',
    appId: '1:416340531176:android:08e4d704e15b0cfb40f65d',
    messagingSenderId: '416340531176',
    projectId: 'bd-app-epis',
    storageBucket: 'bd-app-epis.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2kj8fO4YxGIvqMEfPX0hTvz7CorwRlSQ',
    appId: '1:358709916527:web:abbac1a5ed88d35ad06e9a',
    messagingSenderId: '358709916527',
    projectId: 'upt-tutoria-app',
    authDomain: 'upt-tutoria-app.firebaseapp.com',
    storageBucket: 'upt-tutoria-app.firebasestorage.app',
    measurementId: 'G-D8ZLV3HPCC',
  );

}